spring:
  application:
    name: start-spring
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: Pa55w.rd
stripe:
  apiUrl: https://api.stripe.com
  timeout: 1000
  enabled: true
  supported-currencies: USD, EUR, GBP
payment-gateway: stripe